[project]
name = "pit"
version = "0.1.0"
description = "Minimal git function implemented in Python"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "cleo>=2.1.0",
]

[project.scripts]
hello = "pit:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "coverage>=7.6.3",
    "pytest>=8.3.3",
    "pytest-sugar>=1.0.0",
    "ipykernel>=6.29.5",
]
