[project]
name = "pit"
version = "0.1.0"
description = "Minimal git functions implemented in Python"
readme = "README.md"
requires-python = ">=3.10,<=3.13"
dependencies = [
    "cleo>=2.1.0",
]

[project.scripts]
hello = "pit:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "pytest-sugar>=1.0.0",
    "ipykernel>=6.29.5",
    "pre-commit>=4.0.1",
    "ruff>=0.7.4",
    "pytest-cov>=6.0.0",
]
