name: Pytest in uv venv
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade git to latest
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y
          git config --global user.email "test@mail.com"
          git config --global user.name "test_name"
          git --version

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install the project
        run: uv sync --all-extras --dev
        working-directory: .

      - name: Run tests
        run: uv run pytest tests
        working-directory: .
